import json, collections, statistics as st
L = json.load(open("data/listings.json"))
R = json.load(open("data/rentals.json"))
P = json.load(open("data/projects.json"))
print("counts", len(L), len(R), len(P))
print("\n-- listing field presence / types --")
keys = collections.Counter()
for x in L: keys.update(x.keys())
for k,v in keys.items(): print(f"  {k}: {v}")
print("\nis_live:", collections.Counter(x["is_live"] for x in L))
print("is_verified:", collections.Counter(x["is_verified"] for x in L))
print("website:", collections.Counter(x["website"] for x in L))
print("property_type:", collections.Counter(x["property_type"] for x in L))
print("posted_by:", collections.Counter(x["posted_by"] for x in L))
print("bedroom:", sorted(collections.Counter(x["bedroom"] for x in L).items()))
print("locality:", collections.Counter(x["locality"] for x in L))
pr = sorted(x["price"] for x in L)
print("\nprice min/p1/med/p99/max:", pr[0], pr[len(pr)//100], pr[len(pr)//2], pr[len(pr)*99//100], pr[-1])
ca = sorted(x["carpet_area"] for x in L if x["carpet_area"] is not None)
print("carpet min/med/max:", ca[0], ca[len(ca)//2], ca[-1], "n=", len(ca))
print("\nposted_at samples:", [x["posted_at"] for x in L[:3]])
print("posted_at min/max:", min(x["posted_at"] for x in L), max(x["posted_at"] for x in L))
